CREATE TABLE booking_service."booking" (
                           "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "userID" int,
                           "workplaceID" int,
                           "start_date" timestamp,
                           "end_date" TIMESTAMP,
                           "status" varchar,
                           "created_at" TIMESTAMP
);

Create table booking_service."parking_bookings"(
                                   "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   "user_id" int NOT NULL,
                                    "parking_space_id" int NOT NULL,
                                   "start_time" timestamp NOT NULL,
                                   "end_time" timestamp NOT NULL,
                                   "status" VARCHAR,
                                   "created_at" TIMESTAMP NOT NULL,
                                   FOREIGN KEY ("parking_space_id") REFERENCES resource_service.parking_spaces ("id") ON DELETE SET NULL
);

ALTER TABLE booking_service."booking" ADD FOREIGN KEY ("userID") REFERENCES "users" ("user_id");
ALTER TABLE booking_service."booking" ADD CONSTRAINT check_booking_dates
    CHECK (end_date > start_date);
ALTER TABLE booking_service."booking" ADD FOREIGN KEY ("workplaceID") REFERENCES resource_service.workplace ("id");

ALTER TABLE booking_service."parking_bookings" ADD FOREIGN KEY ("id") REFERENCES auth.users ("user_id");
